bedroom_choices={
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    '10':10
}
price_choices={
    '100000':'$100,000',
    '200000':'$200,000',
    '300000':'$300,000',
    '400000':'$400,000',
    '500000':'$500,000',
    '600000':'$600,000',
    '700000':'$700,000',
    '800000':'$800,000',
    '900000':'$900,000',
    '1000000':'$1M+',

}

state_choices={
    'AK':'Alaska',
                    'AL':'Alabama',
                    'AS':'American Samoa',
                    'AZ':'Arizona',
                    'AR':'Arkansas',
                    'CA':'California',
                    'CO':'Colorado',
                    'CT':'Connecticut',
                    'Dc':'District Of Columbia',
                    'DE':'Delaware',
                    'FL':'Florida',
                    'GA':'Georgia',
                    'GU':'Guam',
                    'HI':'Hawaii',
                    'IA':'Iowa',
                    'ID':'Idaho',
                    'IL':'Illinois',
                    'IN':'Indiana',
                    'KS':'Kansas',
                    'KY':'Kentucky',
                    'LA':'Louisiana',
                    'MA':'Massachusetts',
                    'MD':'Marryland',
                    'ME':'Maine',
                    'MI':'Michigan',
                    'MN':'Minnesota',
                    'MO':'Missouri',
                    'MP':'Northern Mariana Islands',
                    'MS':'Mississippi',
                    'MT':'Montana',
                    'NA':'National',
                    'NC':'North California',
                    'ND':'North Dakota',
                    'NE':'Nebraska',
                    'NH':'New Hamsphire',
                    'NJ':'New Jersey',
                    'NM':'New Mexico',
                    'NV':'Nevada',
                    'NY':'New York',
                    'OH':'Ohio',
                    'OK':'Oklahoma',
                    'OR':'Oregon',
                    'PA':'Pennsylvania',
                    'PR':'Puerto Rico',
                    'RI':'Rhode Island',
                    'SC':'South California',
                    'SD':'South Dakota',
                    'TN':'Tennessee',
                    'TX':'Texas',
                    'UT':'Utah',
                    'VA':'Virginia',
                    'VI':'Virgin Islands',
                    'VT':'Vermont',
                    'WA':'Washington',
                    'WI':'Wisconsin',
                    'WV':'West Virginia',
                    'WY':'Wyoming',
                    'TS':'Telangana'
}